### ISSUE TITLE
bump_dev decreases the version number

### ISSUE THREAD

**Issue by 5j9** [RazerM/parver#7]
`Version.parse('1.2').bump_dev()` returns a version equal to `Version.parse('1.2.dev0')`, but `Version.parse('1.2.dev0') < Version.parse('1.2')`.

**Comment by RazerM** [comment]
The goal of `.bump_dev()` is not to produce a development version number that is higher than the current one, since it doesn't know whether you want that to be e.g. 1.3.dev0 or 1.2.1.dev0. Depending on your workflow you'll want to combine it with `.bump_release()`:

```python
>>> Version.parse('1.2').bump_release(index=1).bump_dev()
<Version '1.3.dev0'>
```

If this behaviour seems surprising maybe it's worth a note in the documentation.

**Comment by 5j9** [comment]
I see, thanks for the explanation. The docs are fine, I should have read them more thoroughly. Knowing about `bump_release()` it now makes more sense.
Nice and useful library by the way. Thanks again.

**Comment by RazerM** [comment]
Thank you!
